###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    mysql:
        container_name: vmmobilka-mysql
        image: 'mysql:8.0'
        working_dir: /application
        volumes:
            - '../:/application'
            - ./mysql_dump:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_ROOT_PASSWORD=123456
            - MYSQL_DATABASE=vmmobilka
            - MYSQL_USER=vmmobilka
            - MYSQL_PASSWORD=123456
        ports:
            - '62001:3306'

    webserver:
        container_name: vmmobilka-webserver
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '../:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '62000:80'

    php-fpm:
        container_name: vmmobilka-phpfpm
        build: phpdocker/php-fpm
        working_dir: /application
        environment:
            - MYSQL_HOST=vmmobilka-mysql
            - MYSQL_DATABASE=vmmobilka
            - MYSQL_USER=vmmobilka
            - MYSQL_PASSWORD=123456
        volumes:
            - '../:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini'
